- name: Setup key for Ubuntu Xenial apt
  become: yes
  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: Setup sources for Ubuntu Xenial apt
  become: yes
  shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: Update sources
  become: yes
  shell: apt-get update

- name: Install MongoDB Community Edition
  become: yes
  apt:
    name: mongodb-org
    state: present
